using System.Collections.Generic;
using UnityEngine;
using Fusion;
public class SpellStateManager : MonoBehaviour
{
    // Singleton instance that keeps track of unique spell instances
    // this allows simul-casting by all connected clients, as well
    // as allowing 'breaks' in the chain (i.e. the host spawns a
    // gameobject, which replaces a client's buffered one).
    // This allows clients to 're-capture' spellstate information,
    // attach on relevant monobeaviours, etc, even when there
    // is a break in the chain due to networked instantiation.

    public static SpellStateManager instance;
    Dictionary<NetworkBehaviourId, int> curr_spell_state_id = new Dictionary<NetworkBehaviourId, int>();
    // spell state ids (i.e. cast ids) will not be the same order
    // across clients/host/proxies, due to when packets arrive and
    // ticks are calculated.
    // but, the cast ids per network object will be ordered the same way
    // ...assuming no missing packets... :( 
    // So instead of just an incrementing int id, we build up an id from
    // a networkbehaviourid and an int id. The int essentially shows
    // the count of casts that object has performed.

    // the only way this gets out-of-sync is if a packet is missed
    // where something (a player/enemy) cast and then they cast again
    // before that packet is received (or its never received).
    // the other option is that each castactioncontroller tracks this
    // state id, to allow us to correct up in case of missed packets.

    public int GetNextSpellStateId(NetworkBehaviour nb)
    {
        if (curr_spell_state_id.ContainsKey(nb))
        {
            curr_spell_state_id[nb]++;
            return curr_spell_state_id[nb];
        }
        else
        {
            curr_spell_state_id.Add(nb, 0);
            return 0;
        }
    }
    // This dictionary contains all spell_states currently in effect.
    // They are indexed by a unique id.
    // These are all local spell states, generated by sharing
    // information.
    // Each casting of a spell receives a unique identifier.
    // This allows us to find it's spell state globally, not just
    // from passing into scripts.
    // The unique identifier of a spellstate is networked and attached
    // to any summoned object.
    Dictionary<SpellStateID, SpellState> local_spell_states = new Dictionary<SpellStateID, SpellState>();
    
    private void Awake()
    {
        instance = this;
        curr_spell_state_id = new Dictionary<NetworkBehaviourId, int>();
    }

    public void AddSpellState(SpellState state)
    {
        Debug.Log($"adding spell state with guid {state.SpellStateID.cast_id}");
        local_spell_states.Add(state.SpellStateID, state);
    }

    public SpellState GetSpellState(SpellStateID guid)
    {
        local_spell_states.TryGetValue(guid, out SpellState state);
        return state;
    }
}
